<?php

$configs = json_decode('
			{
				"index_recent": "6",
				"index_featured": "3",
				"clientid": "your_client_id_here",
				"secretId": "your_client_secret_here",
				"youtube_api_key": "",
				"site_title": "Deikho",
				"site_slogan": "Aur Deikhty Jao ",
				"baseurl": "https://deikho.com",
				"basedir": "/var/www/html",
				"template_dir": "cb_28",
				"player_file": "cb_video_js.php",
				"closed": "",
				"closed_msg": "",
				"description": "Deikho is a video streaming platform.",
				"keywords": "",
				"ffmpegpath": "/opt/bin/ffmpeg",
				"flvtool2path": "",
				"mp4boxpath": "/usr/bin/MP4Box",
				"vbrate": "300000",
				"srate": "44100",
				"r_height": "",
				"r_width": "",
				"resize": "",
				"mencoderpath": "",
				"keep_original": "",
				"activation": "1",
				"mplayerpath": "",
				"email_verification": "1",
				"allow_registeration": "1",
				"php_path": "/usr/bin/php",
				"videos_list_per_page": "30",
				"channels_list_per_page": "25",
				"videos_list_per_tab": "1",
				"channels_list_per_tab": "1",
				"video_comments": "1",
				"video_rating": "1",
				"comment_rating": "1",
				"video_download": "",
				"video_embed": "1",
				"groups_list_per_page": "25",
				"seo": "no",
				"admin_pages": "100",
				"search_list_per_page": "25",
				"recently_viewed_limit": "10",
				"max_upload_size": "1000",
				"sbrate": "320000",
				"thumb_width": "",
				"thumb_height": "",
				"user_comment_opt1": "",
				"ffmpeg_type": "",
				"user_comment_opt2": "",
				"user_comment_opt3": "",
				"user_comment_opt4": "",
				"user_rate_opt1": "",
				"captcha_type": "0",
				"allow_upload": "",
				"allowed_types": "wmv,avi,divx,3gp,mov,mpeg,mpg,xvid,flv,asf,rm,dat,mp4,png,jpg",
				"version": "2.0.1",
				"version_type": "Alpha",
				"allow_template_change": "1",
				"allow_language_change": "",
				"default_site_lang": "",
				"video_require_login": "",
				"audio_codec": "libfdk_aac",
				"con_modules_type": "",
				"remoteUpload": "",
				"embedUpload": "",
				"player_div_id": "",
				"code_dev": "(Powered by ClipBucket)",
				"sys_os": "",
				"debug_level": "",
				"enable_troubleshooter": "1",
				"vrate": "",
				"num_thumbs": "3",
				"big_thumb_width": "",
				"big_thumb_height": "",
				"user_max_chr": "15",
				"disallowed_usernames": "shit, asshole, fucker",
				"min_age_reg": "0",
				"max_comment_chr": "800",
				"user_comment_own": "",
				"anonym_comments": "yes",
				"player_dir": "CB_video_js",
				"player_width": "661",
				"player_height": "360",
				"default_country_iso2": "PK",
				"channel_player_width": "600",
				"channel_player_height": "281",
				"videos_items_grp_page": "1",
				"videos_items_hme_page": "1",
				"videos_items_columns": "1",
				"videos_items_ufav_page": "25",
				"videos_items_uvid_page": "1",
				"videos_items_search_page": "30",
				"videos_item_channel_page": "1",
				"users_items_subscriptions": "5",
				"users_items_subscibers": "5",
				"users_items_contacts_channel": "5",
				"users_items_search_page": "12",
				"users_items_group_page": "15",
				"cbhash": "PGRpdiBhbGlnbj0iY2VudGVyIj48IS0tIERvIG5vdCByZW1vdmUgdGhpcyBjb3B5cmlnaHQgbm90aWNlIC0tPg0KUG93ZXJlZCBieSA8YSBocmVmPSJodHRwOi8vY2xpcC1idWNrZXQuY29tLyI+Q2xpcEJ1Y2tldDwvYT4gJXMgfCA8YSBocmVmPSJodHRwOi8vY2xpcC1idWNrZXQuY29tL2Fyc2xhbi1oYXNzYW4iPkFyc2xhbiBIYXNzYW48L2E+DQo8IS0tIERvIG5vdCByZW1vdmUgdGhpcyBjb3B5cmlnaHQgbm90aWNlIC0tPjwvZGl2Pg==",
				"min_video_title": "4",
				"max_video_title": "8000",
				"min_video_desc": "5",
				"max_video_desc": "3000",
				"video_categories": "10",
				"min_video_tags": "3",
				"max_video_tags": "3000",
				"video_codec": "libx264",
				"date_released": "01-05-2010",
				"date_installed": "01-05-2010",
				"date_updated": "2010-01-09 18:36:16",
				"support_email": "webmaster@localhost",
				"website_email": "webmaster@localhost",
				"welcome_email": "webmaster@localhost",
				"anonymous_id": "159",
				"date_format": "Y-m-d",
				"default_time_zone": "Australia/Adelaide",
				"autoplay_video": "no",
				"channel_comments": "1",
				"max_profile_pic_size": "2500",
				"max_profile_pic_height": "",
				"max_profile_pic_width": "230",
				"gravatars": "no",
				"picture_url": "yes",
				"picture_upload": "yes",
				"background_url": "yes",
				"background_upload": "yes",
				"max_bg_size": "2500",
				"max_bg_width": "1600",
				"max_bg_height": "",
				"background_color": "yes",
				"send_comment_notification": "yes",
				"approve_video_notification": "yes",
				"keep_mp4_as_is": "",
				"hq_output": "",
				"grp_categories": "",
				"grps_items_search_page": "25",
				"grp_thumb_height": "",
				"grp_thumb_width": "",
				"grp_max_title": "",
				"grp_max_desc": "",
				"quick_conv": "",
				"server_friendly_conversion": "",
				"max_conversion": "5",
				"max_time_wait": "7200",
				"allow_unicode_usernames": "",
				"min_username": "3",
				"max_username": "15",
				"youtube_enabled": "yes",
				"allow_username_spaces": "",
				"use_playlist": "yes",
				"comments_captcha": "guests",
				"player_logo_file": "logo.jpg",
				"logo_placement": "tl",
				"buffer_time": "5",
				"use_ffmpeg_vf": "",
				"own_photo_rating": "",
				"mail_type": "mail",
				"smtp_host": "",
				"smtp_user": "",
				"smtp_pass": "",
				"smtp_auth": "no",
				"smtp_port": "",
				"use_subs": "",
				"pak_license": "",
				"photo_ratio": "16:10",
				"photo_thumb_width": "600",
				"photo_thumb_height": "75",
				"photo_med_width": "300",
				"photo_med_height": "116",
				"photo_lar_width": "600",
				"photo_crop": "1",
				"photo_multi_upload": "5",
				"photo_download": "1",
				"photo_comments": "1",
				"photo_rating": "1",
				"max_photo_size": "2",
				"watermark_photo": "0",
				"watermark_max_width": "120",
				"watermark_placement": "left:top",
				"load_upload_form": "yes",
				"load_remote_upload_form": "yes",
				"load_embed_form": "yes",
				"load_link_video_form": "yes",
				"enable_groups": "",
				"groupsSection": "",
				"videosSection": "yes",
				"photosSection": "yes",
				"homeSection": "yes",
				"signupSection": "yes",
				"uploadSection": "yes",
				"collectionsSection": "no",
				"channelsSection": "yes",
				"flvtoolpp": "",
				"normal_resolution": "",
				"high_resolution": "",
				"max_video_duration": "320",
				"embed_player_height": "176",
				"embed_player_width": "300",
				"autoplay_embed": "yes",
				"playlistsSection": "yes",
				"photo_main_list": "1",
				"photo_home_tabs": "1",
				"photo_search_result": "1",
				"photo_channel_page": "1",
				"photo_user_photos": "1",
				"photo_user_favorites": "1",
				"photo_other_limit": "1",
				"collection_per_page": "30",
				"collection_home_page": "10",
				"collection_search_result": "20",
				"collection_channel_page": "10",
				"collection_user_collections": "20",
				"collection_user_favorites": "20",
				"collection_items_page": "20",
				"reCaptcha_private_key": "6LcQI8ESAAAAALc_oz1xuNsBVRNx554CaJHjcoXt",
				"reCaptcha_public_key": "6LcQI8ESAAAAALN1vYQovst9c6nlU52iHdqWExp8",
				"channel_rating": "1",
				"own_channel_rating": "1",
				"collection_rating": "1",
				"own_collection_rating": "1",
				"own_video_rating": "1",
				"vbrate_hd": "",
				"store_guest_session": "no",
				"delete_mass_upload": "no",
				"use_crons": "no",
				"pseudostreaming": "yes",
				"comments_per_page": "15",
				"embed_type": "iframe",
				"feedsSection": "yes",
				"enlarge_button": "no",
				"max_topic_length": "",
				"max_topic_title": "",
				"facebook_embed": "yes",
				"seo_vido_url": "1",
				"use_cached_pagin": "yes",
				"cached_pagin_time": "5",
				"player_logo_url": "http://clip-bucket.com/",
				"cb_combo_res": "yes",
				"ffprobe_path": "/opt/bin/ffprobe",
				"media_info": "/usr/bin/mediainfo",
				"i_magick": "/usr/bin/convert",
				"gen_240": "yes",
				"gen_360": "yes",
				"gen_480": "yes",
				"gen_720": "yes",
				"gen_1080": "yes",
				"photo_activation": "1",
				"stay_mp4": "no",
				"popup_video": "",
				"video_round_views": "yes",
				"vbrate_240": "320000",
				"vbrate_360": "400000",
				"vbrate_480": "480000",
				"vbrate_720": "560000",
				"vbrate_1080": "640000",
				"use_watermark": "",
				"stream_via": "hls",
				"access_to_logged_in": "no",
				"cb_license": "CBCORP-XXXXXXXXXXX",
				"cb_license_local": "",
				"keep_downloadable_files": "yes",
				"disable_embedded_videos": "no",
				"gen_1440": "",
				"gen_2160": "",
				"vbrate_1440": "",
				"vbrate_2160": "",
				"conversion_profile": "",
				"elastic_server_ip": "http://localhost",
				"blocked_countries": "",
				"enable_cat_featured_vid": "no",
				"trending_video": "yes",
				"recent_video": "yes",

				"app_logo": "https://deikho.com/images/logo.png",
				"elastic_search": "yes",

				"vid_categories": [],
				"country_block": "no",
				"paidConfigs": {
				  "currency": "USD",
				  "test_mode": "enabled",
				  "paypal_email": "my@paypal.com",
				  "paypal_sandbox_email": "sandbox@paypal.com",
				  "license_key": "CBPAIDMODXXXXXX",
				  "license_local_key": "",
				  "premium_type": "selected",
				  "premium_videos": "0",
				  "allow_demo": "3.0",
				  "show_prem_icon": "yes",
				  "alertpay_code": "yes",
				  "alertpay_email": "yes",
				  "use_alertpay": "yes",
				  "use_directpay": "yes",
				  "directpay_company_token": "",
				  "directpay_service_type": "",
				  "directpay_service_name": "",
				  "notify_on_sub": "yes",
				  "notify_on_payment": "yes",
				  "email_notification": "yes",
				  "use_first_data": "yes",
				  "fd_api_login": "XXX",
				  "fd_api_key": "XXX123",
				  "fd_store_id": "XXX456",
				  "fd_shared_secret": "XXX",
				  "pay_to_text": "Your pay_to Text",
				  "fd_currency": "840",
				  "paypal_client_id": "AWFF4AUcHLZDLAOpfUo8f0VoJ8VkN3uXhwwrDpBoHV7ow4ojM5A-bY-JA4zf1TAwrf_DxHyr_u5wFzt5",
				  "paypal_secret": "EA2Q8W_fQottezQl0dA1vya8zJbzGbqMeLlI-MqTEhJWmekA6AEA8XixzMth0VvcgaXXJQ1orMF59QrH",
				  "return_url": "https://confidence.vodlix.com/payment",
				  "cancle_url": "https://confidence.vodlix.com/payment/failed",
				  "paypal_rest_api": "yes",
				  "use_stripe": "no",
				  "stripe_email": "my@stripe.com",
				  "stripe_secret": "123",
				  "use_pay_pal": "yes",
				  "use_2co": "yes",
				  "mins_allow_type": "each",
				  "2co_vendor_id": "123465789",
				  "allow_user_set_premium": "yes"
				}
			  }
			  ');

           echo    $config('video_codec');

 $uploadDirectory                            ="/var/www/html/react/php/files/uploads";
 $conversionDirectory                        ="/var/www/html/react/php/files/conversion";
 $logDirectory                               ="/var/www/html/react/php/files/logs";
 $BASEDIR                                    ="/var/www/html";




$fileDirectory                                   ="/var/www/html/react/php/files/uploads/2020/11/16/1187ee0ee667469b94bebd3d52158646/";
$uniqueIdentifier                                ="1187ee0ee667469b94bebd3d52158646";
$fileToConvert                                   ="1187ee0ee667469b94bebd3d52158646.mp4";
$fileName                                        ="1187ee0ee667469b94bebd3d52158646";
$targetFileName                                  ="1187ee0ee667469b94bebd3d52158646.mp4";
//
$year                                            = date("Y");
$month                                           = date("m");
$day                                             = date("d");
//
$conversionDirName                               ="${conversionDirectory}/{$year}/{$month}/{$day}/{$uniqueIdentifier}";
$logFile                                         = $logDirectory.'/'.$uniqueIdentifier;
$logFileName                                     ="$uniqueIdentifier.log";
if (!file_exists($conversionDirName)){
    mkdir($conversionDirName,0777,true);
}
if (!file_exists($logFile)){
    mkdir($logFile,0777,true);
    fopen($logFileName, 'w');
}
echo "reached$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$";
        /*
			Preparing the configurations for video conversion from database
		*/

		$configs = array(
			'use_video_rate' => true,
			'use_video_bit_rate' => true,
			'use_audio_rate' => true,
			'use_audio_bit_rate' => true,
			'use_audio_codec' => true,
			'use_video_codec' => true,
			'format' => 'mp4',
			'video_codec'=> config('video_codec'),
			'audio_codec'=> config('audio_codec'),
			'audio_rate'=> config("srate"),
			'audio_bitrate'=> config("sbrate"),
			'video_rate'=> config("vrate"),
			'video_bitrate_240'=> config("vbrate_240"),
			'video_bitrate_360'=> config("vbrate_360"),
			'video_bitrate_480'=> config("vbrate_480"),
			'video_bitrate_720'=> config("vbrate_720"),
			'video_bitrate_1080'=> config("vbrate_1080"),
			'video_bitrate_hd'=> config("vbrate_hd"),
			'normal_res' => config('normal_resolution'),
			'high_res' => config('high_resolution'),
			'max_video_duration' => config('max_video_duration'),
			'resize'=>'max',
			'outputPath' => $fileDir,
			'cb_combo_res' => config('cb_combo_res'),
			'gen_240' => config('gen_240'),
			'gen_360' => config('gen_360'),
			'gen_480' => config('gen_480'),
			'gen_720' => config('gen_720'),
			'gen_1080' => config('gen_1080'),
			'use_watermark' => config('use_watermark'),
			'stream_via' => config('stream_via'),
			'gen_1440' => config('gen_1440'),
			'gen_2160' => config('gen_2160'),
			'video_bitrate_1440'=> config("vbrate_1440"),
			'video_bitrate_2160'=> config("vbrate_2160"),
			'conv_profile'=> config("conversion_profile"),
		);

		




